### ISSUE TITLE
error sending request 

### ISSUE THREAD

**Issue by kaorlol** [pepperoni21/ollama-rs#17]
Error: Ollama error: error sending request for url (http://127.0.0.1:11434/api/generate): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)

using mistral:latest

**Comment by pepperoni21** [comment]
Hey, did you make sure the Ollama server is running on port 11434 ?

**Comment by kaorlol** [comment]
> Hey, did you make sure the Ollama server is running on port 11434 ?

How do I do that?

**Comment by pepperoni21** [comment]
> > Hey, did you make sure the Ollama server is running on port 11434 ?
> 
> How do I do that?

You need to install ollama on your machine https://ollama.ai/download/linux
