### ISSUE TITLE
Launch the ollama server from within the Rust program?

### ISSUE THREAD

**Issue by mandroll** [pepperoni21/ollama-rs#21]
Thanks for making this extension! Do you know if it's possible to set up the ollama server from within the Rust program, such that one could deploy a standalone application that runs llama2 and makes queries to it?

Feel free to close this issue once answered. Thanks again!

**Comment by pepperoni21** [comment]
Hey, the ollama server being a completely external program, I'd recommend you use Docker for that.

You can create a compose file that deploys the ollama server using the official image https://hub.docker.com/r/ollama/ollama
and you can create your own image of the rust app that interacts with ollama.

**Comment by mandroll** [comment]
Thanks!
