### ISSUE TITLE
Should the "stop" option be defined as a string array?

### ISSUE THREAD

**Issue by dezoito** [pepperoni21/ollama-rs#24]
The `stop` option for completion is defined as an optional String:

```rs
// in src/generation/options.rs
pub struct GenerationOptions {
    pub(super) mirostat: Option<u8>,
    pub(super) mirostat_eta: Option<f32>,
    ...
    pub(super) stop: Option<String>,
   ...
}
```

However, in Ollama, this is defined as a string array [here](https://github.com/ollama/ollama/blob/7c0167a8f6bef322cb78ebf7651083b385e48c8a/api/types.go#L107):

```go
type Options struct {
	Runner

	// Predict options used at runtime
	NumKeep          int      `json:"num_keep,omitempty"`
	...
	Stop             []string `json:"stop,omitempty"`
}
```

Currently, if I set the value of `stop` to something like `["AI Assistant" ]`, that is passed as a string when I make a completion request, and Ollama responds with a `Error: {"error":"option \"stop\" must be of type array"}`.

I can't set it to a vec of string because it is defined as `Option<String>`.

If I am getting something wrong, please let me know.

To clarify, I am using Tauri, and the values for the options are passed from the frontend as JSON strings:

```js

default_options: {
    mirostat: 0,
    mirostat_tau: 5.0,
    mirostat_eta: 0.1,
    num_ctx: 4096,
    num_gqa: 1,
    num_gpu: 50,
    num_thread: 8,
    repeat_last_n: 64,
    repeat_penalty: 1.1,
    temperature: 0.7,
    seed: 42,
    stop: ["AI assistant:"],
    tfs_z: 1,
    num_predict: 42,
    top_k: 40,
    top_p: 0.9,
};
```

**Comment by pepperoni21** [comment]
Hey, I used the official Ollama documentation for the fields and it says that the `stop` field is a string.
![image](https://github.com/pepperoni21/ollama-rs/assets/29759371/3b30af6d-7e4d-44c6-a6f0-9950afce91ab)

I guess that's an error then, I'll fix that now!

**Comment by dezoito** [comment]
They mention some options in their docs that are not even supported (at least, not last time I checked)

I guess they are moving very fast and = as in any project - the docs sometimes struggle to catch up.

Thank you!

**Comment by functorism** [comment]
Can confirm I'm running into the exact same issue, their docs have an example here:

https://github.com/ollama/ollama/blob/main/docs/api.md?plain=1#L312

And looking at the types we can see it's `[]string`:

https://github.com/ollama/ollama/blob/main/api/types.go#L107

**Comment by functorism** [comment]
Here's a fix that I can confirm works on my end: https://github.com/pepperoni21/ollama-rs/pull/26

**Comment by pepperoni21** [comment]
Thanks for the fix!

**Comment by dezoito** [comment]
Working on my end as well.

Thank you, gentlemen!
