### ISSUE TITLE
No streaming option for chat with History 

### ISSUE THREAD

**Issue by khullaa-mcmaster** [pepperoni21/ollama-rs#41]
Trying to understand why streaming isn't supported for send_chat_messages_with_history, is this a limitation of underlying Ollama API?

**Comment by pepperoni21** [comment]
Hey! I don't think it's due to a limitation of Ollama. @ushinnary is there a specific reason or is it an oversight?

**Comment by ushinnary** [comment]
To be honest, i have implemented only no stream option beacause i was need it for my projects. If we stream option, i can try to add it too

**Comment by pepperoni21** [comment]
> To be honest, i have implemented only no stream option beacause i was need it for my projects. If we need a stream option, i can try to add it too

No problem, if you want to add it you can, otherwise I'll do it!

**Comment by ushinnary** [comment]
Yep, i'll do it

**Comment by ushinnary** [comment]
@pepperoni21 after spending some time, I can't find a way to implement it correctly. As we need the `self` to be mutable and operate on it with each iteration, getting error when stream outlives `&mut self`. 
If you have any idea of how to implement chat history for stream, I would like you to share it.
Meanwhile, I will still search for ways to implement it.
Thanks

**Comment by pepperoni21** [comment]
> @pepperoni21 after spending some time, I can't find a way to implement it correctly. As we need the `self` to be mutable and operate on it with each iteration, getting error when stream outlives `&mut self`. If you have any idea of how to implement chat history for stream, I would like you to share it. Meanwhile, I will still search for ways to implement it. Thanks

Hey, yeah I see, we need to find a way to mutate the `self` during the stream, I don't know if it's even possible.

**Comment by RegenJacob** [comment]
I'm not sure if I misunderstand this issue but isn't it just possible to use streaming with history by doing something like this:
```rs
let mut o_req = ollama
    .send_chat_messages_stream(
        ChatMessageRequest::new(
            model.to_string(),
            context_msg,
        )
        .options(GenerationOptions::default()),
    )
    .await?;

```
?

**Comment by ushinnary** [comment]
@RegenJacob didn't see your updated solution. Yes, it may help, but in this case, it's up to you to manage all the history of messages. But I think that we want it to be stored by the library, like it's done without stream, so you don't get all of that overhead.

**Comment by ZBcheng** [comment]
Hey guys, I'm not sure if this can solve the problem:
To ensure messages_history shared between threads safely, I changed it to 
```rust
Option<Arc<RwLock<history::MessagesHistory>>>
```
And I used async-stream to handle stream returned by `send_chat_messages_stream` method
```rust
pub async fn send_chat_messages_with_history_stream(
        &self,
        mut request: ChatMessageRequest,
        id: String,
    ) -> crate::error::Result<ChatMessageResponseStream> {
        let mut current_chat_messages = self.async_get_chat_messages_by_id(id.clone()).await;

        if let Some(message) = request.messages.first() {
            current_chat_messages.push(message.clone());
        }

        // The request is modified to include the current chat messages
        request.messages.clone_from(&current_chat_messages);

        let mut resp_stream: ChatMessageResponseStream =
            self.send_chat_messages_stream(request.clone()).await?;

        let (tx, mut rx) = tokio::sync::mpsc::channel::<ChatMessageResponse>(10);
        let messages_history = self.messages_history.clone();

        tokio::spawn(async move {
            let mut result = String::new();
            while let Some(item) = rx.recv().await {
                if item.done {
                    if let Some(message) = request.messages.last() {
                        if let Some(history) = messages_history.clone() {
                            let mut inner = history.write().await;
                            inner.add_message(id.clone(), message.clone());
                        }
                    }

                    if let Some(history) = messages_history.clone() {
                        let mut inner = history.write().await;
                        inner.add_message(id.clone(), item.message.clone().unwrap());
                    }

                    result = String::new();
                } else {
                    result.push_str(&item.message.clone().unwrap().content);
                }
            }
        });

        let s = stream! {
            while let Some(item) = resp_stream.try_next().await.unwrap() {
                if let Err(e) = tx.send(item.clone()).await {
                    eprintln!("Failed to send stream response: {}", e);
                };

                yield Ok(item);
            }
        };

        Ok(Box::pin(s))
    }
```
Hope it helps :>

**Comment by ushinnary** [comment]
@ZBcheng Thanks for your example. I tried my best, but still have some issues that I can't solve. Would like to see somebody more experienced to realize this feature.

**Comment by izyuumi** [comment]
I tried solving it here: https://github.com/izyuumi/ollama-rs/commit/e553bb713f40ca889a02f01d765027124f02e319

My approach is similar to @ZBcheng's where I'm using Arc and Mutex in a new `MessagesHistoryAsync` struct. My approach still requires the user to save the response, which I believe is not ideal, however, it works. Try the example I made with `cargo run --example chat_with_history_stream`!

**Comment by ZBcheng** [comment]
> I tried solving it here: [izyuumi@e553bb7](https://github.com/izyuumi/ollama-rs/commit/e553bb713f40ca889a02f01d765027124f02e319)
> 
> My approach is similar to @ZBcheng's where I'm using Arc and Mutex in a new `MessagesHistoryAsync` struct. My approach still requires the user to save the response, which I believe is not ideal, however, it works. Try the example I made with `cargo run --example chat_with_history_stream`!
> 
> Edit: ~I'm testing this right now, and seems like the chat history is not properly passed. Will try to fix this.~ It is fixed now ([izyuumi@25aba76](https://github.com/izyuumi/ollama-rs/commit/25aba760f822be9f0faa192ba2c1d4fd89b21290)).

Cool! If you don't want users save the response manually, you can use `stream` macro in `async-trait` to adapt the stream.

**Comment by izyuumi** [comment]
Wow! That worked like magic! @ZBcheng Thank you!!
Now, chat history with stream should work without the user manually storing the result.
https://github.com/izyuumi/ollama-rs/commit/383a3a11fef9cbad67ab49e1212b379000ba672e

**Comment by izyuumi** [comment]
Let me know if you all find any issues with my fix. If not, it could possibly be merged to this repo.
