### ISSUE TITLE
`GenerationFinalResponseData` is `None` due to omitted fields

### ISSUE THREAD

**Issue by erhant** [pepperoni21/ollama-rs#46]
Hi, i would like to be able to get the [`GenerationFinalResponseData`](https://github.com/pepperoni21/ollama-rs/blob/master/src/generation/completion/mod.rs#L112) in a 100% certain way, but it seems it is sometimes there and sometimes not. 

Im using `generate` function, so `stream` should be false anyways. It also appears that if `done` is true, the final data may still be `None`.

**Comment by erhant** [comment]
Hmm this may actually be a bug somewhere, I am looking at the logs of Ollama (im running on a Mac, with `ollama serve`) and apparently sometimes the prompt token count is shown to be 0. When that happens, I get `None` for the final data. 

Here is an example log with a filled `final_data`, we can see the prompt had 98 tokens:

```json
{"function":"print_timings","level":"INFO","line":276,"msg":"prompt eval time     =     369.77 ms /    98 tokens (    3.77 ms per token,   265.03 tokens per second)","n_prompt_tokens_processed":98,"n_tokens_second":265.02602934216753,"slot_id":0,"t_prompt_processing":369.775,"t_token":3.7732142857142854,"task_id":3,"tid":"0x1f699e500","timestamp":1715174643}
```

Here is another log for the same prompt, same settings:

```json
{"function":"print_timings","level":"INFO","line":276,"msg":"prompt eval time     =     206.29 ms /     0 tokens (     inf ms per token,     0.00 tokens per second)","n_prompt_tokens_processed":0,"n_tokens_second":0.0,"slot_id":0,"t_prompt_processing":206.291,"t_token":null,"task_id":65,"tid":"0x1f699e500","timestamp":1715174941}
```

Now we get 0 tokens, and therefore `inf` appears for ms per token. When this happens `final_data` is `None`.

**Comment by erhant** [comment]
A-ha, found it: https://github.com/ollama/ollama/issues/3427

Indeed, if the prompt is cached it will omit the field and cause the entire thing to be `None` on this side.

**Comment by erhant** [comment]
I would like to propose that we write each field explicitly, instead of `#[serde(flatten)]`.

**Comment by pepperoni21** [comment]
That issue rings a bell, I think someone already created an issue for that but we thought it was a bug on ollama side. We need to make this field optional then, I'll do that when I get home.

**Comment by erhant** [comment]
@pepperoni21 I made a quick fix in PR above^

**Comment by dezoito** [comment]
I think I was the one who originally reported this issue here #27 (and also thought it was on Ollama's side as I didn't know about it caching prompts).

@erhant , thank you for the fix... I have read the commit, but I don't understand exactly how that solved the problem.
If you have a few minutes to spare, could you explain how removing serde's `flatten` and making each field an `Option` solved it?

Thanks

**Comment by erhant** [comment]
hi @dezoito, sure!

the thing is when used with `flatten`, a single missing field in the to-be-flattened nested object causes the entire nested object to fail. below is a demonstration:

```rs
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
struct Flattened {
    foo: u32,
    bar: Option<u32>,
    baz: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize)]
struct Nested {
    foo: u32,
    #[serde(flatten)]
    barbaz: Option<NestedInner>,
}

#[derive(Debug, Serialize, Deserialize)]
struct NestedInner {
    bar: u32,
    baz: u32,
}

fn main() {
    const OBJ_NESTED: &str = "{\"foo\": 1, \"bar\": 2, \"baz\": 3}";
    let obj_nested: Nested = serde_json::from_str(OBJ_NESTED).unwrap();
    println!("{:?}", obj_nested);

    const OBJ_FLATTENED: &str = "{\"foo\": 1, \"bar\": 2, \"baz\": 3}";
    let obj_flattened: Flattened = serde_json::from_str(OBJ_FLATTENED).unwrap();
    println!("{:?}", obj_flattened);

    const OBJ_NESTED_MISSING: &str = "{\"foo\": 1, \"bar\": 2}";
    let obj_nested_missing: Nested = serde_json::from_str(OBJ_NESTED_MISSING).unwrap();
    println!("{:?}", obj_nested_missing);

    const OBJ_FLATTENED_MISSING: &str = "{\"foo\": 1, \"bar\": 2}";
    let obj_flattened_missing: Flattened = serde_json::from_str(OBJ_FLATTENED_MISSING).unwrap();
    println!("{:?}", obj_flattened_missing);
}
```

When we run it, we see the result:

```sh
Nested    { foo: 1, barbaz: Some(NestedInner { bar: 2, baz: 3 }) }
Flattened { foo: 1, bar: Some(2), baz: Some(3) }

Nested    { foo: 1, barbaz: None }
Flattened { foo: 1, bar: Some(2), baz: None }
```

So although `bar` existed in the 3rd example, since `baz` didn't exist the entire `barbaz` failed and we missed the `bar` data. This was the case with Ollama, as it didnt return one of the fields in the final data, causing the entire thing to be lost.

Perhaps there is a better serde feature that does the fix for this instead of manually flattening the nested `Option` object to separate `Option` fields. That I don't know!

**Comment by dezoito** [comment]
Thank you! Much appreciated.
