### ISSUE TITLE
How can the parameter "keep_alive": -1, be sent in a generate_embeddings request ?

### ISSUE THREAD

**Issue by 0xSchellen** [pepperoni21/ollama-rs#57]
It seems that there is no parameter to set  "keep_alive": -1 in the Struct Generation Options.

The idea is to load the embedding model and keeping it in the memory.

**Comment by pepperoni21** [comment]
Hey, you can do that:
```rust
let request = GenerationRequest::new(...).keep_alive(KeepAlive::Indefinitely);
```
Is that what you meant?

**Comment by 0xSchellen** [comment]
Hi! Thanks for the response! 

This works fine for the Completions API.

But i can´t use it in the generate_embeddings  trait.

    let response = ollama
        .generate_embeddings(model.to_string(), prompt, None)
        .await?;

**Comment by pepperoni21** [comment]
Sorry for the delay, I'll fix that
