### ISSUE TITLE
Why is GenerateEmbeddingsResponse Vec<f64> instead of Vec<f32>? 

### ISSUE THREAD

**Issue by RegenJacob** [pepperoni21/ollama-rs#70]
It appears that Ollama generates 32-bit floats for its embeddings.

See this line of code: https://github.com/ollama/ollama/blob/108fb6c1d1c33265dc8f10073f9540e76b820ef9/api/types.go#L268

However, the `GenerateEmbeddingsResponse` type in the API outputs a vector of 64-bit floating-point numbers (`Vec<f64>`). Is there a specific reason for this?

**Comment by pepperoni21** [comment]
I don't remember the specific reason why I chose f64 over f32 but yeah it does look wrong, I'll make a PR
