### ISSUE TITLE
Feature Request: Add Support for Custom HTTP Headers in Ollama Requests

### ISSUE THREAD

**Issue by itsscb** [pepperoni21/ollama-rs#72]
Hello there,

I discovered **Ollama** a few months ago and forgot about it. 

Yesterday I came across it again and promptly set up an instance at home on a dedicated machine and made it publicly accessible behind a reverse proxy that authenticates using basic auth, because I wanted to be able to access it from anywhere - even though it runs on old hardware and takes ages to answer. But it works and I would like to experiment with it. 

As I'm a *Rustacean* I was going to write a library for Rust myself. But it seems like you guys were faster :-)

Unfortunately, as I see it, it is currently not possible to set **any** request headers. That makes it impossible for me to use this crate with my setup, as I do quite some work on the road and can't set up a VPN due to technicalities. 

So I thought for myself that I can't be the only one with a setup like this and came up with three possible solutions which I would like to propose from (*my*) most to least favorite.

| ID | Proposal | Pros | Cons |
| --- | --- | --- | --- |
| 1 | Accept a `reqwest::header::HeaderMap` and use `RequestBuilder.headers()` on each occurence of `Ollama.reqwest_client`. Maybe re-export the required structs and constants from the `reqwest` crate? | <ul><li>Allows users to define headers as they please</li><li>Future proof</li></ul> | <ul><li>Has to be applied to each `Ollama.reqwest_client` occurence</li><li>Requires additional implementation work</li></ul> |
|2 | Accept a `Option<Credential>` in the `Ollama` struct and use the `RequestBuilder.basic_auth()` on each occurence | <ul><li>Quick and dirty</li></ul>| <ul><li>Quick and dirty</li><li>Has to be applied to each `Ollama.request_client` occurence</li><li>Not future proof</li></ul>  |
|3 | Pass in the `host` Parameter using the old school `https://[username]:[password]...` scheme (presumably no change in code required) | <li>Should work without any code changes</li> | <ul><li>Insecure</li><li>Not future proof</li></ul>  |

Another approach would be to separate the crate completely from the engine that runs the requests (currently the `reqwest` crate). But that would certainly break all existing projects. And up to this point I couldn't figure out how this could be achieved.

I would be happy to contribute the changes on which we agree, should we agree.

The first and second approach have already been successfully tested in my local fork (not yet published).

Please let me know what you think and if this could be beneficial for this crate.

PS: Maybe this could be implemented behind a *feature flag*.

**Comment by pepperoni21** [comment]
Hey, sorry for the delay. The first approach actually sounds very good. I can implement it if needed but if you already have an implementation of it then the contribution would be welcome!

**Comment by spotlesscoder** [comment]
I also need authentication to be supported.
The first proposed approach sounds most promising to me
