### ISSUE TITLE
removal index (is 0) should be < len (is 0)

### ISSUE THREAD

**Issue by ShayBox** [pepperoni21/ollama-rs#73]
`removal index (is 0) should be < len (is 0)` https://github.com/pepperoni21/ollama-rs/blob/master/src/history.rs#L42

This panics if there's no messages (sending the first message), also there can be multiple system messages, and the system message could be at any point in the list, not just the start.

**Comment by pepperoni21** [comment]
Yeah makes sense, I'll fix that
