### ISSUE TITLE
The GenerationFinalResponseData struct is missing load_duration.

### ISSUE THREAD

**Issue by nate34k** [pepperoni21/ollama-rs#8]
I noticed that the field for load_duration in the GenerationFinalResponseData struct was removed, yet it still exists in the API. Is it going to be coming back or is there a larger issue with it I am unaware of?

**Comment by pepperoni21** [comment]
Hey, by running the tests I noticed that this field was not included anymore in the responses which caused an error while parsing the response so I thought it was just removed

**Comment by nate34k** [comment]
After further testing, it seems that is the case, and they just didn't update their API docs.
