### ISSUE TITLE
`no suitable llama servers found`

### ISSUE THREAD

**Issue by InAnYan** [pepperoni21/ollama-rs#83]
I've written an application that uses ollama-rs.

`ollama` is running on my machine. My app could successfully pull models, but as soon as I start to generate chat messages or generate embeddings, I have this error:

```
{"error":"no suitable llama servers found"}
```

Super strange error.

Specs: Linux Mint 22, x86_64, Rust 1.82, ollama-rs 0.2.1

**Comment by pepperoni21** [comment]
Hey, do you also get this error while using the cli? Might be an issue on ollama side

**Comment by InAnYan** [comment]
Oh, you are right. When I call `ollama run tinyllama` I have the same error.

This is strange. `ollama serve` tells that the address is bound - and I confirmed it's bound to ollama process.

I never actually had this problem before with ollama :)

**Comment by pepperoni21** [comment]
It seems to be an issue with the llama model, you might find a solution here: https://github.com/ollama/ollama/issues/5944

**Comment by InAnYan** [comment]
Yes, yes, googled it right now.

Sorry, I'll close the issue, it is not connected to ollama-rs.

Though, the error message is quite confusing

**Comment by pepperoni21** [comment]
No problem! :)
